In [ ]:
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest# for univarient selection
from sklearn.feature_selection import chi2

In [ ]:
filename='/content/pima-indians-diabetes.data.csv'
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe = read_csv(filename,names=names)
array=dataframe.values
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [ ]:
X = array[:,0:8]
Y = array[:,8]# seperate them in a x n y only 8 th col is considered here

#feature extraction
test=SelectKBest(score_func=chi2,k=5)#best 5 features
fit = test.fit(X,Y)
#summarize scores
set_printoptions(precision=4)
print(fit.scores_)#will get chio square for each feature
features= fit.transform(X)
# 2175.5653 is highest chi  value so its most imp

[ 111.5197 1411.887    17.6054   53.108  2175.5653  127.6693    5.3927
  181.3037]


In [ ]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
type(test)

sklearn.feature_selection._univariate_selection.SelectKBest

In [ ]:
x=pd.DataFrame(fit.scores_).T # .T will transpose list into dataframe

In [ ]:
x# only index is visible not col names

0            1          2         3            4           5  \
0  111.519691  1411.887041  17.605373  53.10804  2175.565273  127.669343   

          6           7  
0  5.392682  181.303689

In [ ]:
x.columns=names[:8]
x#as per chi test is most important feature next pass

preg         plas       pres      skin         test        mass  \
0  111.519691  1411.887041  17.605373  53.10804  2175.565273  127.669343   

       pedi         age  
0  5.392682  181.303689

Recursive feature elimination

In [ ]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
#load data
filename='/content/pima-indians-diabetes.data.csv'
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe = read_csv(filename,names=names)
array=dataframe.values
X = array[:,0:8]
Y = array[:,8]
#feature extraction
model=LogisticRegression(max_iter=400)
rfe = RFE(model)
fit = rfe.fit(X, Y)

In [ ]:
#num feature :4 top fea are avail
fit.n_features_

4

In [ ]:
#select feature ;
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [ ]:
names #print column names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
#feature ranking
fit.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

In [ ]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

feature importance using Decision tree

In [ ]:
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier
#load data
filename='/content/pima-indians-diabetes.data.csv'
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe = read_csv(filename,names=names)
array=dataframe.values
X = array[:,0:8]
Y = array[:,8]
#feature extraction
model=DecisionTreeClassifier()
model.fit(X, Y)
print(model.feature_importances_)#feature importance score

[0.0699 0.3121 0.0951 0.0203 0.0324 0.2281 0.11   0.1321]


In [ ]:
names #plas is imp feaeature , then mass , age pedi
 # find common am ongst all methods

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']